apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rclone.fullname" . }}-init
  labels:
{{ include "rclone.labels" . | indent 4 }}
data:
{{ toYaml .Values.init.runScript | indent 2}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rclone.fullname" . }}-rclone
  labels:
{{ include "rclone.labels" . | indent 4 }}
data:
{{ toYaml .Values.cfgRclone | indent 2}}